file_names = {
    "dataset_name": "1_movielens_dataset.csv",
    "train_set": "2_train_set.pkl",
    "test_set": "2_test_set.pkl",
    "user_mapping": "2_user_mapping.pkl",
    "user_reverse_mapping": "2_user_reverse_mapping.pkl",
    "item_mapping": "2_item_mapping.pkl",
    "item_reverse_mapping": "2_item_reverse_mapping.pkl",
    "user_item_mappings": "2_user_item_mappings.pkl",
    "user_item_matrix": "2_user_item_matrix.pkl",
    "movieId_tmdbId_mapping": "2_movieId_tmdbId_mapping.pkl",
    "user_matrix": "3_user_matrix.pkl",
    "item_matrix": "3_item_matrix.pkl",
    "user_means": "3_user_means.pkl",
    "item_means": "3_item_means.pkl",
    "user_item_means": "3_user_item_means.pkl",
    "svd_user_model": "3_svd_user_model.pkl",
    "svd_item_model": "3_svd_item_model.pkl",
    "svd_components": "3_svd_components.pkl",
    "model_info": "3_model_info.pkl",
    "model_components": "3_model_components.pkl",
    "faiss_user_index": "4_user_index.faiss",
    "faiss_item_index": "4_item_index.faiss",
}
